# Movielens clustering

In [70]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.cluster import KMeans

In [71]:
df_movies = pd.read_csv('movies.csv')
df_ratings = pd.read_csv('ratings.csv')
df = pd.merge(df_movies,df_ratings)
df

,movieId,title,genres,userId,rating,timestamp
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,1,4.0,964982703
1,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,5,4.0,847434962
2,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,7,4.5,1106635946
3,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,15,2.5,1510577970
4,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,17,4.5,1305696483
5,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,18,3.5,1455209816
6,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,19,4.0,965705637
7,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,21,3.5,1407618878
8,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,27,3.0,962685262
9,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,31,5.0,850466616
10,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,32,3.0,856736119
11,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,33,3.0,939647444
12,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,40,5.0,832058959
13,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,43,5.0,848993983
14,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,44,3.0,869251860
15,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,45,4.0,951170182
16,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,46,5.0,834787906
17,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,50,3.0,1514238116
18,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,54,3.0,830247330
19,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,57,5.0,965796031
20,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,63,5.0,1443199669
21,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,64,4.0,1161520134
22,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,66,4.0,1104643957
23,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,68,2.5,1158531426
24,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,71,5.0,864737933
25,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,73,4.5,1464196374
26,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,76,0.5,1439165548
27,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,78,4.0,1252575124
28,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,82,2.5,1084467729
29,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,86,4.0,1344082549
...,...,...,...,...,...,...
100806,188301,Ant-Man and the Wasp (2018),Action|Adventure|Comedy|Fantasy|Sci-Fi,596,4.0,1535709468
100807,188675,Dogman (2018),Crime|Drama,318,3.5,1535035470
100808,188751,Mamma Mia: Here We Go Again! (2018),Comedy|Romance,212,4.5,1532362151
100809,188797,Tag (2018),Comedy,514,4.0,1535941279
100810,188833,The Man Who Killed Don Quixote (2018),Adventure|Comedy|Fantasy,318,4.5,1535035971
100811,189043,Boundaries (2018),Comedy|Drama,338,2.5,1530148447
100812,189111,Spiral (2018),Documentary,338,3.0,1530148343
100813,189333,Mission: Impossible - Fallout (2018),Action|Adventure|Thriller,184,4.0,1537110051
100814,189333,Mission: Impossible - Fallout (2018),Action|Adventure|Thriller,248,3.5,1534602181
100815,189381,SuperFly (2018),Action|Crime|Thriller,318,2.5,1536097988
100816,189547,Iron Soldier (2010),Action|Sci-Fi,210,1.0,1528486011
100817,189713,BlacKkKlansman (2018),Comedy|Crime|Drama,462,2.5,1536467299
100818,190183,The Darkest Minds (2018),Sci-Fi|Thriller,50,3.5,1533302021
100819,190207,Tilt (2011),Drama|Romance,338,1.5,1530148481
100820,190209,Jeff Ross Roasts the Border (2017),Comedy,338,4.0,1530148487
100821,190213,John From (2015),Drama,338,1.0,1530148478
100822,190215,Liquid Truth (2017),Drama,338,1.5,1530148477
100823,190219,Bunny (1998),Animation,338,1.0,1530148473
100824,190221,Hommage à Zgougou (et salut à Sabine Mamou) (2...,Documentary,338,1.0,1530148473
100825,191005,Gintama (2017),Action|Adventure|Comedy|Sci-Fi,184,4.5,1537109489
100826,193565,Gintama: The Movie (2010),Action|Animation|Comedy|Sci-Fi,184,3.5,1537098554
100827,193567,anohana: The Flower We Saw That Day - The Movi...,Animation|Drama,184,3.0,1537099103
100828,193571,Silver Spoon (2014),Comedy|Drama,184,4.0,1537099392
100829,193573,Love Live! The School Idol Movie (2015),Animation,184,4.0,1537099811
100830,193579,Jon Stewart Has Left the Building (2015),Documentary,184,3.5,1537107259
100831,193581,Black Butler: Book of the Atlantic (2017),Action|Animation|Comedy|Fantasy,184,4.0,1537109082
100832,193583,No Game No Life: Zero (2017),Animation|Comedy|Fantasy,184,3.5,1537109545
100833,193585,Flint (2017),Drama,184,3.5,1537109805
100834,193587,Bungo Stray Dogs: Dead Apple (2018),Action|Animation,184,3.5,1537110021
100835,193609,Andrew Dice Clay: Dice Rules (1991),Comedy,331,4.0,1537157606

In [72]:
ratings = pd.pivot_table(df, index="userId", columns = "title", values='rating')
ratings.head(3)

title,'71 (2014),'Hellboy': The Seeds of Creation (2004),'Round Midnight (1986),'Salem's Lot (2004),'Til There Was You (1997),'Tis the Season for Love (2015),"'burbs, The (1989)",'night Mother (1986),(500) Days of Summer (2009),*batteries not included (1987),...,Zulu (2013),[REC] (2007),[REC]² (2009),[REC]³ 3 Génesis (2012),anohana: The Flower We Saw That Day - The Movie (2013),eXistenZ (1999),xXx (2002),xXx: State of the Union (2005),¡Three Amigos! (1986),À nous la liberté (Freedom for Us) (1931)
userId,,,,,,,,,,,,,,,,,,,,,
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.0,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [73]:
ratings = ratings.reindex(ratings.count().sort_values(ascending=False).index, axis=1)
ratings.head(3)

title,Forrest Gump (1994),"Shawshank Redemption, The (1994)",Pulp Fiction (1994),"Silence of the Lambs, The (1991)","Matrix, The (1999)",Star Wars: Episode IV - A New Hope (1977),Jurassic Park (1993),Braveheart (1995),Terminator 2: Judgment Day (1991),Schindler's List (1993),...,"Last Wedding, The (Kivenpyörittäjän kylä) (1995)","Last Winter, The (2006)",Last Year's Snow Was Falling (1983),Last of the Dogmen (1995),Late Marriage (Hatuna Meuheret) (2001),Late Night Shopping (2001),Late Night with Conan O'Brien: The Best of Triumph the Insult Comic Dog (2004),"Late Shift, The (1996)",Latter Days (2003),'71 (2014)
userId,,,,,,,,,,,,,,,,,,,,,
1,4.0,NaN,3.0,4.0,5.0,5.0,4.0,4.0,NaN,5.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [74]:
ratings_full = ratings.fillna(0) #fill the NaN with the mean of each column
ratings_full.head(3)

title,Forrest Gump (1994),"Shawshank Redemption, The (1994)",Pulp Fiction (1994),"Silence of the Lambs, The (1991)","Matrix, The (1999)",Star Wars: Episode IV - A New Hope (1977),Jurassic Park (1993),Braveheart (1995),Terminator 2: Judgment Day (1991),Schindler's List (1993),...,"Last Wedding, The (Kivenpyörittäjän kylä) (1995)","Last Winter, The (2006)",Last Year's Snow Was Falling (1983),Last of the Dogmen (1995),Late Marriage (Hatuna Meuheret) (2001),Late Night Shopping (2001),Late Night with Conan O'Brien: The Best of Triumph the Insult Comic Dog (2004),"Late Shift, The (1996)",Latter Days (2003),'71 (2014)
userId,,,,,,,,,,,,,,,,,,,,,
1,4.0,0.0,3.0,4.0,5.0,5.0,4.0,4.0,0.0,5.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.5,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [75]:
km = KMeans(n_clusters=4) #create a new k-means model with 3 clusters
X = ratings_full #get the X variables from the dataframe
km = km.fit(X) #calculate the cluster centers
ratings["cluster"] = km.predict(X) #predict the clusters of each observation and store in the dataframe
ratings.head()

title,Forrest Gump (1994),"Shawshank Redemption, The (1994)",Pulp Fiction (1994),"Silence of the Lambs, The (1991)","Matrix, The (1999)",Star Wars: Episode IV - A New Hope (1977),Jurassic Park (1993),Braveheart (1995),Terminator 2: Judgment Day (1991),Schindler's List (1993),...,"Last Winter, The (2006)",Last Year's Snow Was Falling (1983),Last of the Dogmen (1995),Late Marriage (Hatuna Meuheret) (2001),Late Night Shopping (2001),Late Night with Conan O'Brien: The Best of Triumph the Insult Comic Dog (2004),"Late Shift, The (1996)",Latter Days (2003),'71 (2014),cluster
userId,,,,,,,,,,,,,,,,,,,,,
1,4.0,NaN,3.0,4.0,5.0,5.0,4.0,4.0,NaN,5.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
2,NaN,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2
4,NaN,NaN,1.0,5.0,1.0,5.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
5,NaN,3.0,5.0,NaN,NaN,NaN,NaN,4.0,3.0,5.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2

In [76]:
ratings["cluster"].value_counts()

2    476
1     73
0     47
3     14
Name: cluster, dtype: int64

In [86]:
ratings = ratings.reindex(ratings.count().sort_values(ascending=False).index, axis=1)
ratings

title,cluster,Forrest Gump (1994),"Shawshank Redemption, The (1994)",Pulp Fiction (1994),"Silence of the Lambs, The (1991)","Matrix, The (1999)",Star Wars: Episode IV - A New Hope (1977),Jurassic Park (1993),Braveheart (1995),Terminator 2: Judgment Day (1991),...,Let the Bullets Fly (2010),"Last Wave, The (1977)",Let's Get Harry (1986),"League of Ordinary Gentlemen, A (2004)",Last Year's Snow Was Falling (1983),Le Maître d'école (1981),Last Orders (2001),Late Night Shopping (2001),Last Shift (2014),Latter Days (2003)
userId,,,,,,,,,,,,,,,,,,,,,
1,0,4.0,NaN,3.0,4.0,5.0,5.0,4.0,4.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,NaN,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,0,NaN,NaN,1.0,5.0,1.0,5.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,2,NaN,3.0,5.0,NaN,NaN,NaN,NaN,4.0,3.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,2,5.0,5.0,2.0,4.0,NaN,NaN,5.0,5.0,3.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,2,5.0,NaN,NaN,5.0,NaN,5.0,5.0,NaN,2.5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,2,3.0,5.0,4.0,4.0,NaN,NaN,4.0,3.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,2,3.5,NaN,1.0,NaN,0.5,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,2,5.0,4.0,NaN,5.0,NaN,NaN,4.0,5.0,4.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,2,NaN,NaN,NaN,NaN,5.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,2,4.0,3.0,3.0,4.0,NaN,NaN,3.0,5.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,2,5.0,5.0,4.0,NaN,4.0,5.0,NaN,NaN,5.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,2,3.5,4.0,3.0,3.0,3.5,3.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,2,5.0,5.0,5.0,4.5,5.0,5.0,4.5,4.5,4.5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,1,4.5,5.0,4.0,4.5,4.5,4.0,3.5,4.5,4.5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,0,2.0,NaN,NaN,NaN,4.0,4.0,2.0,NaN,5.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,1,4.5,NaN,3.5,NaN,4.0,4.5,4.0,NaN,3.5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,2,5.0,5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,2,NaN,NaN,3.5,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,2,4.5,4.5,4.0,4.5,4.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,2,NaN,NaN,NaN,NaN,5.0,5.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,2,3.0,NaN,4.0,4.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,2,5.0,NaN,NaN,NaN,NaN,4.0,4.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,1,4.0,3.5,4.5,2.5,4.0,4.0,2.5,3.5,4.5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,2,4.5,4.5,3.5,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30,2,NaN,5.0,NaN,NaN,5.0,5.0,NaN,5.0,3.5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
581,2,4.5,5.0,NaN,NaN,3.5,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
582,2,NaN,NaN,NaN,4.0,5.0,4.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
583,2,4.0,NaN,4.0,2.5,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
584,2,5.0,NaN,3.0,4.0,NaN,NaN,5.0,5.0,5.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
585,2,NaN,NaN,5.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
586,1,NaN,5.0,NaN,NaN,5.0,4.5,NaN,5.0,5.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
587,2,4.0,NaN,5.0,NaN,4.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
588,2,3.0,5.0,5.0,5.0,NaN,NaN,3.0,5.0,3.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
589,2,5.0,5.0,5.0,5.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
590,3,5.0,4.5,4.5,3.5,4.0,5.0,4.0,4.0,4.5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
591,2,4.0,NaN,NaN,NaN,5.0,5.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
592,2,5.0,4.0,4.0,5.0,NaN,NaN,5.0,5.0,5.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
593,2,4.0,4.5,NaN,4.0,2.5,5.0,NaN,3.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
594,2,NaN,NaN,NaN,5.0,5.0,NaN,5.0,5.0,5.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
595,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
596,1,3.5,NaN,NaN,4.0,4.0,4.0,NaN,NaN,3.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.5
597,0,5.0,NaN,NaN,NaN,NaN,5.0,5.0,5.0,5.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
598,2,NaN,NaN,NaN,0.5,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
599,3,3.5,4.0,5.0,3.0,5.0,5.0,4.0,3.5,4.5,...,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
600,1,4.0,3.5,4.5,4.0,3.0,4.0,3.0,2.0,3.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
601,2,NaN,5.0,NaN,NaN,5.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
602,2,3.0,5.0,5.0,5.0,NaN,5.0,4.0,5.0,5.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
603,0,3.0,NaN,5.0,5.0,5.0,4.0,NaN,1.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
604,2,NaN,NaN,5.0,5.0,NaN,NaN,NaN,3.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
605,2,3.0,NaN,2.0,NaN,NaN,5.0,3.0,3.0,3.5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
606,1,4.0,3.5,5.0,4.5,5.0,4.5,2.5,3.5,3.5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
607,0,NaN,5.0,3.0,5.0,5.0,3.0,4.0,5.0,4.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
608,3,3.0,4.5,5.0,4.0,5.0,3.5,3.0,4.0,3.0,...,NaN,NaN,NaN,4.0,NaN,NaN,NaN,NaN,NaN,NaN
609,2,4.0,4.0,4.0,NaN,NaN,NaN,3.0,3.0,3.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
610,3,3.0,3.0,5.0,4.5,5.0,5.0,5.0,4.5,5.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.0,NaN

In [99]:
mean_per_cluster = ratings.groupby(ratings["cluster"]).mean()
mean_per_cluster

title,Forrest Gump (1994),"Shawshank Redemption, The (1994)",Pulp Fiction (1994),"Silence of the Lambs, The (1991)","Matrix, The (1999)",Star Wars: Episode IV - A New Hope (1977),Jurassic Park (1993),Braveheart (1995),Terminator 2: Judgment Day (1991),Schindler's List (1993),...,Let the Bullets Fly (2010),"Last Wave, The (1977)",Let's Get Harry (1986),"League of Ordinary Gentlemen, A (2004)",Last Year's Snow Was Falling (1983),Le Maître d'école (1981),Last Orders (2001),Late Night Shopping (2001),Last Shift (2014),Latter Days (2003)
cluster,,,,,,,,,,,,,,,,,,,,,
0,3.932432,4.450000,4.243243,4.342105,4.111111,4.306818,3.750000,4.125000,4.196970,4.300000,...,NaN,3.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,4.186567,4.541667,4.433333,4.173469,4.169118,4.208333,3.705882,3.950000,3.978723,4.262500,...,NaN,NaN,NaN,NaN,5.0,NaN,NaN,4.5,NaN,3.5
2,4.201422,4.408879,4.086735,4.115169,4.209375,4.187970,3.762590,4.038462,3.907692,4.189286,...,NaN,NaN,NaN,NaN,NaN,4.0,NaN,NaN,NaN,NaN
3,4.107143,4.192308,4.607143,4.214286,4.321429,4.500000,3.785714,4.000000,4.000000,4.350000,...,3.0,NaN,NaN,4.0,NaN,NaN,3.0,NaN,4.0,NaN

### Cluster 0

In [143]:
cluster_0 = mean_per_cluster.iloc[0]
cluster_0 = cluster_0.sort_values(ascending=False)
cluster_0.head(4)

title
Man Who Fell to Earth, The (1976)              5.0
You Can't Take It with You (1938)              5.0
All That Heaven Allows (1955)                  5.0
Dinner Game, The (Dîner de cons, Le) (1998)    5.0
Name: 0, dtype: float64

### Cluster 1

In [144]:
cluster_1 = mean_per_cluster.iloc[1]
cluster_1 = cluster_1.sort_values(ascending=False)
cluster_1.head(4)

title
Conversations with Other Women (2005)            5.0
Like Stars on Earth (Taare Zameen Par) (2007)    5.0
Marat/Sade (1966)                                5.0
Come and See (Idi i smotri) (1985)               5.0
Name: 1, dtype: float64

### Cluster 2

In [140]:
cluster_2 = mean_per_cluster.iloc[2]
cluster_2 = cluster_2.sort_values(ascending=False)
cluster_2.head(4)

title
Lincoln (2012)                          5.0
Batman: Mask of the Phantasm (1993)     5.0
The Night Before (2015)                 5.0
A Flintstones Christmas Carol (1994)    5.0
Name: 2, dtype: float64

### Cluster 3

In [145]:
cluster_3 = mean_per_cluster.iloc[3]
cluster_3 = cluster_3.sort_values(ascending=False)
cluster_3.head(4)

title
Cyrano de Bergerac (1990)                               5.0
Black Cat, White Cat (Crna macka, beli macor) (1998)    5.0
Night on Earth (1991)                                   5.0
Show Me Love (Fucking Åmål) (1998)                      5.0
Name: 3, dtype: float64